// Auto-generated by scripts/build-governance-catalog.ts.
// Do not edit by hand — re-run `npm run build:governance` (or any `npm run build`)
// to regenerate from vendor/data-governance/.
import type { VocabularyGroup } from "./types";

export const vocabularyGroups: VocabularyGroup[] = [
  {
    "domain": "audit",
    "application": "Audit Dashboard",
    "group": "ReportType",
    "description": "Classification of audit report documents",
    "values": [
      {
        "code": "FULL_REPORT",
        "label": "Full Report",
        "displayOrder": 1,
        "description": "Complete audit report with all findings and recommendations"
      },
      {
        "code": "FOLLOW_UP",
        "label": "Follow-Up Report",
        "displayOrder": 2,
        "description": "Report on status of previously identified observations"
      },
      {
        "code": "LETTER",
        "label": "Letter Report",
        "displayOrder": 3,
        "description": "Abbreviated report in letter format"
      }
    ]
  },
  {
    "domain": "audit",
    "application": "Audit Dashboard",
    "group": "ObservationStatus",
    "description": "Lifecycle status of an audit observation",
    "values": [
      {
        "code": "OPEN",
        "label": "Open",
        "displayOrder": 1,
        "description": "Observation has been identified and is awaiting action"
      },
      {
        "code": "IN_PROGRESS",
        "label": "In Progress",
        "displayOrder": 2,
        "description": "Corrective action is underway"
      },
      {
        "code": "CLOSED",
        "label": "Closed",
        "displayOrder": 3,
        "description": "Observation has been fully resolved"
      },
      {
        "code": "CLOSED_FIRST_FOLLOWUP",
        "label": "Closed at First Follow Up",
        "displayOrder": 4,
        "description": "Observation resolved and verified at the first follow-up review"
      }
    ]
  },
  {
    "domain": "audit",
    "application": "Audit Dashboard",
    "group": "ActionItemStatus",
    "description": "Lifecycle status of a corrective action item",
    "values": [
      {
        "code": "OPEN",
        "label": "Open",
        "displayOrder": 1,
        "description": "Action item has been created but work has not started"
      },
      {
        "code": "IN_PROGRESS",
        "label": "In Progress",
        "displayOrder": 2,
        "description": "Work on the action item is underway"
      },
      {
        "code": "COMPLETED",
        "label": "Completed",
        "displayOrder": 3,
        "description": "Action item has been fulfilled"
      },
      {
        "code": "OVERDUE",
        "label": "Overdue",
        "displayOrder": 4,
        "description": "Action item has passed its target completion date"
      },
      {
        "code": "CLOSED",
        "label": "Closed",
        "displayOrder": 5,
        "description": "Action item has been verified and closed"
      }
    ]
  },
  {
    "domain": "audit",
    "application": "Audit Dashboard",
    "group": "Severity",
    "description": "Severity level of an audit observation",
    "values": [
      {
        "code": "HIGH",
        "label": "High",
        "displayOrder": 1,
        "description": "Significant risk requiring immediate attention"
      },
      {
        "code": "MEDIUM",
        "label": "Medium",
        "displayOrder": 2,
        "description": "Moderate risk requiring timely remediation"
      },
      {
        "code": "LOW",
        "label": "Low",
        "displayOrder": 3,
        "description": "Minor risk or process improvement opportunity"
      }
    ]
  },
  {
    "domain": "audit",
    "application": "Audit Dashboard",
    "group": "AssignmentRole",
    "description": "Roles assigned to personnel for audit action items",
    "values": [
      {
        "code": "IMPLEMENTER",
        "label": "Implementing Employee",
        "displayOrder": 1,
        "description": "Person responsible for executing the corrective action"
      },
      {
        "code": "REVIEWER",
        "label": "Reviewing Manager",
        "displayOrder": 2,
        "description": "Manager responsible for verifying corrective action completion"
      }
    ]
  },
  {
    "domain": "audit",
    "application": "Audit Dashboard",
    "group": "Priority",
    "description": "Priority level for scheduling and resource allocation",
    "values": [
      {
        "code": "HIGH",
        "label": "High",
        "displayOrder": 1,
        "description": "Requires immediate attention and resource allocation"
      },
      {
        "code": "MEDIUM",
        "label": "Medium",
        "displayOrder": 2,
        "description": "Standard priority for normal workflow"
      },
      {
        "code": "LOW",
        "label": "Low",
        "displayOrder": 3,
        "description": "Can be addressed as resources allow"
      }
    ]
  },
  {
    "domain": "audit",
    "application": "Audit Dashboard",
    "group": "DocumentType",
    "description": "Classification of documents associated with audits",
    "values": [
      {
        "code": "SOURCE_PDF",
        "label": "Source Audit PDF",
        "displayOrder": 1,
        "description": "Original audit report PDF for data extraction"
      },
      {
        "code": "EVIDENCE",
        "label": "Supporting Evidence",
        "displayOrder": 2,
        "description": "Documentation supporting corrective action completion"
      },
      {
        "code": "CORRESPONDENCE",
        "label": "Correspondence",
        "displayOrder": 3,
        "description": "Communications related to audit findings"
      },
      {
        "code": "OTHER",
        "label": "Other Document",
        "displayOrder": 4,
        "description": "Other document types not otherwise classified"
      }
    ]
  },
  {
    "domain": "audit",
    "application": "Audit Dashboard",
    "group": "ExtractionStatus",
    "description": "Status of AI-assisted data extraction from audit documents",
    "values": [
      {
        "code": "PENDING",
        "label": "Pending",
        "displayOrder": 1,
        "description": "Document uploaded but extraction has not started"
      },
      {
        "code": "OCR_IN_PROGRESS",
        "label": "OCR In Progress",
        "displayOrder": 2,
        "description": "Optical character recognition is running"
      },
      {
        "code": "OCR_COMPLETE",
        "label": "OCR Complete",
        "displayOrder": 3,
        "description": "OCR finished, text is available for LLM processing"
      },
      {
        "code": "LLM_IN_PROGRESS",
        "label": "LLM In Progress",
        "displayOrder": 4,
        "description": "Large language model is extracting structured data"
      },
      {
        "code": "REVIEW_PENDING",
        "label": "Awaiting Human Review",
        "displayOrder": 5,
        "description": "Extraction complete, awaiting human verification"
      },
      {
        "code": "APPROVED",
        "label": "Approved",
        "displayOrder": 6,
        "description": "Extracted data has been verified and approved"
      },
      {
        "code": "REJECTED",
        "label": "Rejected",
        "displayOrder": 7,
        "description": "Extracted data was rejected and requires re-processing"
      },
      {
        "code": "FAILED",
        "label": "Failed",
        "displayOrder": 8,
        "description": "Extraction process encountered an unrecoverable error"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Submission_Category",
    "description": "Type of content submitted to the newsletter",
    "values": [
      {
        "code": "faculty_staff",
        "label": "Faculty/Staff",
        "displayOrder": 1,
        "description": "General faculty and staff announcements"
      },
      {
        "code": "student",
        "label": "Student",
        "displayOrder": 2,
        "description": "Student-focused announcements and information"
      },
      {
        "code": "job_opportunity",
        "label": "Job Opportunity",
        "displayOrder": 3,
        "description": "Employment and position listings"
      },
      {
        "code": "kudos",
        "label": "Kudos",
        "displayOrder": 4,
        "description": "Recognition and achievements"
      },
      {
        "code": "in_memoriam",
        "label": "In Memoriam",
        "displayOrder": 5,
        "description": "Memorial notices for community members"
      },
      {
        "code": "news_release",
        "label": "News Release",
        "displayOrder": 6,
        "description": "Official university news releases"
      },
      {
        "code": "calendar_event",
        "label": "Calendar Event",
        "displayOrder": 7,
        "description": "Upcoming events and calendar items"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Newsletter_Type",
    "description": "Newsletter publications produced by UCM",
    "values": [
      {
        "code": "tdr",
        "label": "The Daily Register",
        "displayOrder": 1,
        "description": "Faculty and staff newsletter"
      },
      {
        "code": "myui",
        "label": "My UI",
        "displayOrder": 2,
        "description": "Student newsletter"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Target_Newsletter",
    "description": "Which newsletter(s) a submission is intended for",
    "values": [
      {
        "code": "tdr",
        "label": "TDR Only",
        "displayOrder": 1,
        "description": "Publish only in The Daily Register"
      },
      {
        "code": "myui",
        "label": "My UI Only",
        "displayOrder": 2,
        "description": "Publish only in My UI"
      },
      {
        "code": "both",
        "label": "Both",
        "displayOrder": 3,
        "description": "Publish in both newsletters"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Submission_Status",
    "description": "Lifecycle status of a newsletter submission",
    "values": [
      {
        "code": "new",
        "label": "New",
        "displayOrder": 1,
        "description": "Newly received submission, not yet processed"
      },
      {
        "code": "ai_edited",
        "label": "AI Edited",
        "displayOrder": 2,
        "description": "Submission has been processed by the AI editing pipeline"
      },
      {
        "code": "in_review",
        "label": "In Review",
        "displayOrder": 3,
        "description": "Under editorial review by UCM staff"
      },
      {
        "code": "approved",
        "label": "Approved",
        "displayOrder": 4,
        "description": "Approved for publication"
      },
      {
        "code": "scheduled",
        "label": "Scheduled",
        "displayOrder": 5,
        "description": "Assigned to a specific newsletter edition"
      },
      {
        "code": "published",
        "label": "Published",
        "displayOrder": 6,
        "description": "Published in a newsletter edition"
      },
      {
        "code": "rejected",
        "label": "Rejected",
        "displayOrder": 7,
        "description": "Declined for publication"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Newsletter_Status",
    "description": "Lifecycle status of a newsletter edition",
    "values": [
      {
        "code": "draft",
        "label": "Draft",
        "displayOrder": 1,
        "description": "Edition is being assembled"
      },
      {
        "code": "in_progress",
        "label": "In Progress",
        "displayOrder": 2,
        "description": "Active editing and layout in progress"
      },
      {
        "code": "ready_for_review",
        "label": "Ready for Review",
        "displayOrder": 3,
        "description": "Edition is complete and awaiting final review"
      },
      {
        "code": "submitted",
        "label": "Submitted",
        "displayOrder": 4,
        "description": "Submitted for distribution"
      },
      {
        "code": "published",
        "label": "Published",
        "displayOrder": 5,
        "description": "Edition has been distributed"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Version_Type",
    "description": "Type of content version in the editing pipeline",
    "values": [
      {
        "code": "original",
        "label": "Original",
        "displayOrder": 1,
        "description": "Original submitted text"
      },
      {
        "code": "ai_suggested",
        "label": "AI Suggested",
        "displayOrder": 2,
        "description": "AI-generated edited version"
      },
      {
        "code": "editor_final",
        "label": "Editor Final",
        "displayOrder": 3,
        "description": "Final version after human editor review"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Headline_Case",
    "description": "Capitalization style for headlines",
    "values": [
      {
        "code": "sentence_case",
        "label": "Sentence Case",
        "displayOrder": 1,
        "description": "Only first word and proper nouns capitalized"
      },
      {
        "code": "title_case",
        "label": "Title Case",
        "displayOrder": 2,
        "description": "Major words capitalized"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Rule_Set",
    "description": "Which newsletter(s) a style rule applies to",
    "values": [
      {
        "code": "shared",
        "label": "Shared",
        "displayOrder": 1,
        "description": "Rule applies to both newsletters"
      },
      {
        "code": "tdr",
        "label": "TDR",
        "displayOrder": 2,
        "description": "Rule applies only to The Daily Register"
      },
      {
        "code": "myui",
        "label": "My UI",
        "displayOrder": 3,
        "description": "Rule applies only to My UI"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Severity",
    "description": "Severity level for style rule violations",
    "values": [
      {
        "code": "error",
        "label": "Error",
        "displayOrder": 1,
        "description": "Must be corrected before publication"
      },
      {
        "code": "warning",
        "label": "Warning",
        "displayOrder": 2,
        "description": "Should be reviewed but may be acceptable"
      },
      {
        "code": "info",
        "label": "Info",
        "displayOrder": 3,
        "description": "Informational suggestion only"
      }
    ]
  },
  {
    "domain": "communications",
    "application": "UCM Daily Register",
    "group": "Schedule_Mode",
    "description": "Publication schedule mode based on academic calendar",
    "values": [
      {
        "code": "academic_year",
        "label": "Academic Year",
        "displayOrder": 1,
        "description": "Regular academic year schedule (daily)"
      },
      {
        "code": "summer",
        "label": "Summer",
        "displayOrder": 2,
        "description": "Summer schedule (reduced frequency)"
      }
    ]
  },
  {
    "domain": "iids-portfolio",
    "application": "IIDS Portfolio",
    "group": "ProjectStatus",
    "description": "Operational ladder for a project — the day-to-day status IIDS tracks. Source of truth: lib/portfolio.ts. Each value's Verification_Rule is enforced by lib/portfolio-verification.ts on every PR.",
    "values": [
      {
        "code": "idea",
        "label": "Idea",
        "displayOrder": 1,
        "description": "Named with a unit-of-interest; not yet committed to build.",
        "verificationRule": "No committed operationalOwner OR no committed iidsSponsor; repoUrl empty or repo has zero commits."
      },
      {
        "code": "approved",
        "label": "Approved",
        "displayOrder": 2,
        "description": "Committed to build with named owner and sponsor; not yet under active development.",
        "verificationRule": "operationalOwners[0] set AND iidsSponsor set AND non-empty description; no liveUrl; repo (if present) has <10 commits OR no commits in last 14 days."
      },
      {
        "code": "building",
        "label": "Building",
        "displayOrder": 3,
        "description": "Active development. Code exists but not yet for real users.",
        "verificationRule": "repoUrl set; lastCommitDate within last 60 days; no liveUrl (or liveUrl flagged liveUrlIsStaging:true); pilotCohort empty."
      },
      {
        "code": "prototype",
        "label": "Prototype",
        "displayOrder": 4,
        "description": "Demo-able but quiet — feature-complete or paused.",
        "verificationRule": "pilotCohort empty; either lastCommitDate older than 30 days OR featureComplete:true."
      },
      {
        "code": "piloting",
        "label": "Piloting",
        "displayOrder": 5,
        "description": "In use by a bounded, named cohort.",
        "verificationRule": "liveUrl set; pilotCohort populated with size > 0 and a bounded scope."
      },
      {
        "code": "production",
        "label": "Production",
        "displayOrder": 6,
        "description": "In real institutional use beyond the pilot cohort.",
        "verificationRule": "Publicly-accessible artifact: liveUrl OR a public repoUrl (isPrivateRepo:false) for repo-as-artifact deliverables (infrastructure, scaffolds, appliances). productionScope and supportContact populated."
      },
      {
        "code": "maintained",
        "label": "Maintained",
        "displayOrder": 7,
        "description": "In production but in maintenance-only mode.",
        "verificationRule": "Inherits production accessibility (liveUrl or public repo); no commits to main in last 90 days; no open feature issues — only bug-, security-, or chore-labeled."
      },
      {
        "code": "sunsetting",
        "label": "Sunsetting",
        "displayOrder": 8,
        "description": "Being wound down with a planned successor.",
        "verificationRule": "sunsetDate (ISO) set; replacedBy populated — successor project slug or the literal 'manual-process'."
      },
      {
        "code": "archived",
        "label": "Archived",
        "displayOrder": 9,
        "description": "Stopped. Record kept for institutional memory.",
        "verificationRule": "liveUrl returns 404 / is null / domain dead, or (for repo-as-artifact) repoUrl is archived/deleted; service stopped."
      },
      {
        "code": "tracked",
        "label": "Tracked",
        "displayOrder": 10,
        "description": "Externally-owned project IIDS observes but does not build.",
        "verificationRule": "trackingOnly:true; bypasses the operational ladder."
      }
    ]
  },
  {
    "domain": "iids-portfolio",
    "application": "IIDS Portfolio",
    "group": "PublicStage",
    "description": "Stakeholder-facing rollup. Computed deterministically from ProjectStatus by lib/portfolio.ts:computePublicStage. The public surfaces (/portfolio cards primary chip, landing stat strip, /explore tile breakdowns) render this axis; operational status is only shown as a secondary detail on cards.",
    "values": [
      {
        "code": "exploring",
        "label": "Exploring",
        "displayOrder": 1,
        "description": "Thinking about it / committed to build.",
        "verificationRule": "Rolls up from ProjectStatus values: idea, approved."
      },
      {
        "code": "building",
        "label": "Building",
        "displayOrder": 2,
        "description": "Code exists; not yet for real users.",
        "verificationRule": "Rolls up from ProjectStatus values: building, prototype."
      },
      {
        "code": "live",
        "label": "Live",
        "displayOrder": 3,
        "description": "In use today.",
        "verificationRule": "Rolls up from ProjectStatus values: piloting, production, maintained."
      },
      {
        "code": "retired",
        "label": "Retired",
        "displayOrder": 4,
        "description": "Done or winding down.",
        "verificationRule": "Rolls up from ProjectStatus values: sunsetting, archived."
      },
      {
        "code": "tracked",
        "label": "Tracked",
        "displayOrder": 5,
        "description": "Not built by IIDS.",
        "verificationRule": "Rolls up from ProjectStatus value: tracked. Bypasses the operational ladder."
      }
    ]
  },
  {
    "domain": "iids-portfolio",
    "application": "IIDS Portfolio",
    "group": "ProductionScope",
    "description": "Granularity of production reach. Required on ProjectStatus values production and maintained.",
    "values": [
      {
        "code": "home-unit",
        "label": "Home Unit",
        "displayOrder": 1,
        "description": "Accessible to all users in the project's home unit."
      },
      {
        "code": "institution-wide",
        "label": "Institution-Wide",
        "displayOrder": 2,
        "description": "Accessible to all UI users."
      },
      {
        "code": "external",
        "label": "External",
        "displayOrder": 3,
        "description": "Deployed beyond UI — partner institutions, open-source distribution, or self-hostable artifact consumed externally."
      }
    ]
  },
  {
    "domain": "iids-portfolio",
    "application": "IIDS Portfolio",
    "group": "Visibility",
    "description": "Public-site disclosure level for a project's record.",
    "values": [
      {
        "code": "Public",
        "label": "Public",
        "displayOrder": 1,
        "description": "All fields shown publicly."
      },
      {
        "code": "Partial",
        "label": "Partial",
        "displayOrder": 2,
        "description": "Entry acknowledged on the public site; deployment details (scope, timelines, configuration) embargoed."
      },
      {
        "code": "Internal-only",
        "label": "Internal Only",
        "displayOrder": 3,
        "description": "Not shown on the public site."
      }
    ]
  },
  {
    "domain": "iids-portfolio",
    "application": "IIDS Portfolio",
    "group": "AI4RARelationship",
    "description": "How a project relates to the AI4RA partnership (UI + Southern Utah University NSF GRANTED).",
    "values": [
      {
        "code": "Core",
        "label": "Core",
        "displayOrder": 1,
        "description": "AI4RA OSS project with a UI deployment — dual-destiny."
      },
      {
        "code": "Adjacent",
        "label": "Adjacent",
        "displayOrder": 2,
        "description": "Related to AI4RA but not part of the partnership proper."
      },
      {
        "code": "Reference",
        "label": "Reference",
        "displayOrder": 3,
        "description": "UI deployment consumes an AI4RA spec or tool."
      },
      {
        "code": "UI-parallel",
        "label": "UI-Parallel",
        "displayOrder": 4,
        "description": "UI work running alongside an AI4RA initiative."
      },
      {
        "code": "None",
        "label": "None",
        "displayOrder": 5,
        "description": "No AI4RA relationship."
      }
    ]
  },
  {
    "domain": "iids-portfolio",
    "application": "IIDS Portfolio",
    "group": "WorkCategory",
    "description": "By-problem axis for browsing the portfolio. Audience-facing labels written in a Dean's vocabulary (not technical jargon). Source of truth: lib/work-categories.ts. One project can sit in 2-3 categories.",
    "values": [
      {
        "code": "documents",
        "label": "Working with documents",
        "displayOrder": 1,
        "description": "Extracting, reviewing, or finding answers in documents — contracts, reports, RFPs, audit findings."
      },
      {
        "code": "process",
        "label": "Streamlining a process",
        "displayOrder": 2,
        "description": "Mapping, automating, or removing bottlenecks from operational workflows."
      },
      {
        "code": "coordination",
        "label": "Coordinating people and time",
        "displayOrder": 3,
        "description": "Calendars, schedules, daily registers, multi-party logistics."
      },
      {
        "code": "reconciliation",
        "label": "Reconciling accounts and records",
        "displayOrder": 4,
        "description": "Financial reviews, audit cycles, matching transactions to source data."
      },
      {
        "code": "executive-analytics",
        "label": "Executive visibility",
        "displayOrder": 5,
        "description": "Dashboards, strategic alignment, portfolio-level rollups for leadership."
      },
      {
        "code": "research-admin",
        "label": "Research administration",
        "displayOrder": 6,
        "description": "Proposal lifecycle, awards, sponsor compliance, ORED operations."
      },
      {
        "code": "knowledge-retrieval",
        "label": "Searching institutional knowledge",
        "displayOrder": 7,
        "description": "Retrieval and Q&A over policies, history, decisions — RAG-style."
      },
      {
        "code": "ai-infrastructure",
        "label": "AI infrastructure",
        "displayOrder": 8,
        "description": "LLM gateways, GPU stacks, agent platforms — the plumbing other projects run on, not a problem on its own."
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "ActivityType",
    "description": "Transcript-derived activity classes used during process extraction and analysis",
    "values": [
      {
        "code": "DATA_ENTRY",
        "label": "Data Entry",
        "description": "Entering or updating data in a system"
      },
      {
        "code": "REVIEW_APPROVAL",
        "label": "Review / Approval",
        "description": "Reviewing information and granting or denying approval"
      },
      {
        "code": "SYSTEM_LOOKUP",
        "label": "System Lookup",
        "description": "Looking up information in a system for reference or verification"
      },
      {
        "code": "DOCUMENT_GENERATION",
        "label": "Document Generation",
        "description": "Creating or generating a document, report, or correspondence"
      },
      {
        "code": "COMMUNICATION",
        "label": "Communication",
        "description": "Sending or receiving communication (email, notification, phone call)"
      },
      {
        "code": "DECISION_POINT",
        "label": "Decision Point",
        "description": "Evaluating conditions and choosing a path forward"
      },
      {
        "code": "CALCULATION_VALIDATION",
        "label": "Calculation / Validation",
        "description": "Performing calculations or validating data accuracy"
      },
      {
        "code": "FILING_ARCHIVAL",
        "label": "Filing / Archival",
        "description": "Filing documents or archiving records for retention"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "ActorRole",
    "description": "Recurring research-administration roles referenced in process maps",
    "values": [
      {
        "code": "GRANTS_SPECIALIST",
        "label": "Grants Specialist",
        "description": "OSP staff member who processes awards and proposals"
      },
      {
        "code": "GRANTS_OFFICER",
        "label": "Grants Officer",
        "description": "Senior OSP staff with signing authority"
      },
      {
        "code": "PI",
        "label": "Principal Investigator",
        "description": "Lead researcher on a project"
      },
      {
        "code": "DEPT_ADMIN",
        "label": "Department Administrator",
        "description": "Department-level administrative support"
      },
      {
        "code": "FISCAL_OFFICER",
        "label": "Fiscal Officer",
        "description": "Financial management staff"
      },
      {
        "code": "COMPLIANCE_OFFICER",
        "label": "Compliance Officer",
        "description": "Staff responsible for regulatory compliance"
      },
      {
        "code": "SPONSOR",
        "label": "Sponsor",
        "description": "External funding agency"
      },
      {
        "code": "POST_AWARD_SPECIALIST",
        "label": "Post-Award Specialist",
        "description": "OSP staff member who processes post-award modifications including amendments, rebudgets, PI changes, and no-cost extensions"
      },
      {
        "code": "FINANCIAL_UNIT_SPECIALIST",
        "label": "Financial Unit Specialist",
        "description": "Financial unit staff member who sets up new awards in Banner, verifies billing configuration, and manages financial reporting events"
      },
      {
        "code": "PRE_AWARD_SPA",
        "label": "Pre-Award Sponsored Programs Administrator",
        "description": "OSP staff member who reviews proposals, checks document completeness, and manages pre-award submission processes"
      },
      {
        "code": "DGA",
        "label": "Departmental Grant Administrator",
        "description": "Department-level administrator who manages grant activities and serves as liaison between PI and OSP"
      },
      {
        "code": "PRE_AWARD_MANAGER",
        "label": "Pre-Award Manager",
        "description": "OSP supervisor who oversees pre-award SPA team, manages workload distribution, provides weekly metrics, and leads bi-weekly workload meetings"
      },
      {
        "code": "AOR",
        "label": "Authorized Organizational Representative",
        "description": "University official with authority to submit proposals and sign awards on behalf of the institution"
      },
      {
        "code": "SENIOR_GRANTS_ANALYST",
        "label": "Senior Grants & Contracts Analyst",
        "description": "Senior OSP analyst who handles complex grant and contract administration"
      },
      {
        "code": "SPONSORED_PROGRAMS_OFFICER",
        "label": "Sponsored Programs Officer",
        "description": "OSP officer who oversees sponsored program administration and compliance"
      },
      {
        "code": "ASSISTANT_DIRECTOR_SPONSORED_ACCOUNTING",
        "label": "Assistant Director for Sponsored Accounting",
        "description": "Senior financial staff who oversees sponsored accounting functions including final billing and financial reporting"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "ActorType",
    "description": "High-level categories for actors inside a process map",
    "values": [
      {
        "code": "PERSON",
        "label": "Person",
        "description": "A specific individual"
      },
      {
        "code": "ROLE",
        "label": "Role",
        "description": "A role that could be filled by different people (e.g., Grants Specialist)"
      },
      {
        "code": "SYSTEM",
        "label": "System",
        "description": "A software system or automated process"
      },
      {
        "code": "EXTERNAL",
        "label": "External",
        "description": "An external entity (sponsor, subrecipient, vendor)"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "DocumentType",
    "description": "Document classifications for materials referenced in process maps and workflows — award documents, funding announcements, budget forms, proposal narratives, subaward agreements, and sponsor correspondence",
    "values": [
      {
        "code": "AWARD_NOTICE",
        "label": "Award Notice / Agreement",
        "description": "Fully executed award agreements, federal notices of award, cooperative agreements, research terms and conditions, and related award-establishing documents"
      },
      {
        "code": "AWARD_MODIFICATION",
        "label": "Award Modification",
        "description": "Post-award amendments including modifications, no-cost extensions, PI changes, rebudget approvals, and amendment letters"
      },
      {
        "code": "FUNDING_OPPORTUNITY",
        "label": "Funding Opportunity (FOA/NOFO/RFA)",
        "description": "Funding opportunity announcements, notices of funding opportunity, requests for applications, program announcements, and program solicitations"
      },
      {
        "code": "BUDGET_DOCUMENT",
        "label": "Budget Form / Spreadsheet / Justification",
        "description": "R&R and SF-424A budget forms, budget spreadsheets, budget justification narratives, and sponsor-specific budget pages (NIH modular, NSF detailed)"
      },
      {
        "code": "PROPOSAL_NARRATIVE",
        "label": "Proposal Narrative & Personnel Forms",
        "description": "Proposal documents, project narratives, research plans, biosketches, current and pending support, and VERAS proposal forms with personnel listings"
      },
      {
        "code": "SUBAWARD_DOCUMENT",
        "label": "Subaward / Subrecipient Agreement",
        "description": "Subaward agreements, subrecipient agreements, pass-through entity subaward documents, and subaward modifications"
      },
      {
        "code": "COMPLIANCE_RECORD",
        "label": "Compliance / Personnel Reference Record",
        "description": "SFI disclosure confirmations, RST completion records, Banner NBAJOBS records, departmental personnel lists, and institutional policy references (APM)"
      },
      {
        "code": "SPONSOR_CORRESPONDENCE",
        "label": "Sponsor Correspondence & Guidance",
        "description": "Sponsor correspondence, agency financial reporting guides, and other ad-hoc communications or guidance documents from the funding agency"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "FileType",
    "description": "Source transcript file formats accepted into governed transcript workflows",
    "values": [
      {
        "code": "VTT",
        "label": "WebVTT",
        "description": "Web Video Text Tracks format — caption/subtitle file from video recording"
      },
      {
        "code": "TXT",
        "label": "Plain Text",
        "description": "Plain text transcript file"
      },
      {
        "code": "DOCX",
        "label": "Word Document",
        "description": "Microsoft Word document with transcript notes"
      },
      {
        "code": "MD",
        "label": "Markdown",
        "description": "Markdown-formatted transcript file"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "ProcessCategory",
    "description": "Institutional process families represented by canonical process maps",
    "values": [
      {
        "code": "PRE_AWARD",
        "label": "Pre-Award",
        "description": "Processes related to proposal preparation, submission, and pre-award activities"
      },
      {
        "code": "POST_AWARD",
        "label": "Post-Award",
        "description": "Processes related to award setup, management, and closeout"
      },
      {
        "code": "COMPLIANCE",
        "label": "Compliance",
        "description": "Processes related to regulatory compliance (IRB, IACUC, COI, etc.)"
      },
      {
        "code": "FINANCIAL",
        "label": "Financial",
        "description": "Processes related to financial management, budgeting, and reporting"
      },
      {
        "code": "SUBAWARD",
        "label": "Subaward",
        "description": "Processes related to subaward issuance, monitoring, and closeout"
      },
      {
        "code": "REPORTING",
        "label": "Reporting",
        "description": "Processes related to progress reports, financial reports, and deliverables"
      },
      {
        "code": "CONTRACTING",
        "label": "Contracting",
        "description": "Processes related to agreements, contracts, and negotiations"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "ProcessingStatus",
    "description": "Transcript processing stages from raw ingestion through structured mapping",
    "values": [
      {
        "code": "RAW",
        "label": "Raw",
        "description": "Transcript is in its original unprocessed form"
      },
      {
        "code": "PARSED",
        "label": "Parsed",
        "description": "Transcript has been parsed into structured segments but not yet mapped to a process"
      },
      {
        "code": "MAPPED",
        "label": "Mapped",
        "description": "Transcript has been fully mapped to one or more structured process definitions"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "RedactionStatus",
    "description": "PII redaction review states tracked for transcript assets",
    "values": [
      {
        "code": "NOT_REDACTED",
        "label": "Not Redacted",
        "description": "Transcript has not been reviewed for PII redaction"
      },
      {
        "code": "PARTIALLY_REDACTED",
        "label": "Partially Redacted",
        "description": "Some PII has been redacted but review may be incomplete"
      },
      {
        "code": "FULLY_REDACTED",
        "label": "Fully Redacted",
        "description": "All PII has been reviewed and redacted"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "StepType",
    "description": "Process-step types used inside canonical process maps",
    "values": [
      {
        "code": "ACTION",
        "label": "Action",
        "description": "A step where an actor performs a specific action"
      },
      {
        "code": "DECISION",
        "label": "Decision",
        "description": "A branching point where the process flow depends on a condition"
      },
      {
        "code": "REVIEW",
        "label": "Review",
        "description": "A step where information is reviewed or evaluated"
      },
      {
        "code": "APPROVAL",
        "label": "Approval",
        "description": "A step where formal approval is granted or denied"
      },
      {
        "code": "DATA_ENTRY",
        "label": "Data Entry",
        "description": "A step where data is entered into a system"
      },
      {
        "code": "COMMUNICATION",
        "label": "Communication",
        "description": "A step involving communication (email, phone, meeting)"
      },
      {
        "code": "WAIT",
        "label": "Wait",
        "description": "A step where the process pauses for external input or a time period"
      },
      {
        "code": "SUBPROCESS",
        "label": "Subprocess",
        "description": "A step that references another process map"
      }
    ]
  },
  {
    "domain": "processmapping",
    "application": "ProcessMapping",
    "group": "SystemName",
    "description": "Institutional and external systems referenced in process maps",
    "values": [
      {
        "code": "BANNER",
        "label": "Banner",
        "description": "Ellucian Banner ERP system for financial and student records"
      },
      {
        "code": "CAYUSE",
        "label": "Cayuse",
        "description": "Research administration software for proposals and IRB"
      },
      {
        "code": "GRANTS_GOV",
        "label": "Grants.gov",
        "description": "Federal grant application portal"
      },
      {
        "code": "RESEARCH_GOV",
        "label": "Research.gov",
        "description": "NSF research administration portal"
      },
      {
        "code": "ERA_COMMONS",
        "label": "eRA Commons",
        "description": "NIH electronic research administration"
      },
      {
        "code": "SAM_GOV",
        "label": "SAM.gov",
        "description": "System for Award Management"
      },
      {
        "code": "EMAIL",
        "label": "Email",
        "description": "Email communication system"
      },
      {
        "code": "VANDALIZER",
        "label": "Vandalizer",
        "description": "AI document intelligence platform"
      },
      {
        "code": "VERAS",
        "label": "VERAS",
        "description": "InfoEd VERAS research administration system for proposal and award management, workflow tracking, and correspondence"
      },
      {
        "code": "EXCEL",
        "label": "Microsoft Excel",
        "description": "Spreadsheet application used for personal tracking, data analysis, and workload management"
      },
      {
        "code": "TEAMS",
        "label": "Microsoft Teams",
        "description": "Collaboration platform used for file sharing and team communication"
      },
      {
        "code": "EXPORT_TO_BANNER_FORM",
        "label": "Export to Banner Form",
        "description": "VERAS form used to configure how proposal/award data exports to Banner, including index codes, fund codes, and cost share distribution codes"
      },
      {
        "code": "CHROME_RIVER",
        "label": "Chrome River",
        "description": "Travel and expense management system for processing reimbursements and expense reports"
      },
      {
        "code": "JAGGAER",
        "label": "JAGGAER",
        "description": "Procurement system for vendor payments, purchase orders, and Q-Doc processing"
      },
      {
        "code": "KUALI",
        "label": "Kuali",
        "description": "Research compliance system for COI, IRB, and IACUC protocols"
      },
      {
        "code": "ARGOS",
        "label": "Argos",
        "description": "Reporting tool for financial reports, due dates, and payroll data from Banner"
      },
      {
        "code": "SOFTDOCS",
        "label": "SoftDocs/eRetrieve",
        "description": "Document management and retrieval system for journal entry documentation"
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "DocumentType",
    "description": "Types of documents included in a proposal submission package",
    "values": [
      {
        "code": "proposal_narrative",
        "label": "Proposal Narrative",
        "displayOrder": 1
      },
      {
        "code": "budget_justification",
        "label": "Budget Justification",
        "displayOrder": 2
      },
      {
        "code": "biosketch",
        "label": "Biographical Sketch",
        "displayOrder": 3
      },
      {
        "code": "current_pending",
        "label": "Current & Pending Support",
        "displayOrder": 4
      },
      {
        "code": "facilities",
        "label": "Facilities & Equipment",
        "displayOrder": 5
      },
      {
        "code": "data_mgmt",
        "label": "Data Management Plan",
        "displayOrder": 6
      },
      {
        "code": "letter_support",
        "label": "Letter of Support",
        "displayOrder": 7
      },
      {
        "code": "rfa_document",
        "label": "RFA/RFP Document",
        "displayOrder": 8
      },
      {
        "code": "subaward_docs",
        "label": "Subaward Documents",
        "displayOrder": 9
      },
      {
        "code": "coi_disclosure",
        "label": "COI Disclosure",
        "displayOrder": 10
      },
      {
        "code": "other",
        "label": "Other Document",
        "displayOrder": 11
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ProjectRole",
    "description": "Roles of personnel on sponsored research projects",
    "values": [
      {
        "code": "pi",
        "label": "Principal Investigator",
        "displayOrder": 1
      },
      {
        "code": "co_pi",
        "label": "Co-Principal Investigator",
        "displayOrder": 2
      },
      {
        "code": "co_i",
        "label": "Co-Investigator",
        "displayOrder": 3
      },
      {
        "code": "key_person",
        "label": "Key Personnel",
        "displayOrder": 4
      },
      {
        "code": "senior_person",
        "label": "Senior Personnel",
        "displayOrder": 5
      },
      {
        "code": "postdoc",
        "label": "Postdoctoral Researcher",
        "displayOrder": 6
      },
      {
        "code": "grad_student",
        "label": "Graduate Student",
        "displayOrder": 7
      },
      {
        "code": "undergrad",
        "label": "Undergraduate Student",
        "displayOrder": 8
      },
      {
        "code": "technician",
        "label": "Technician",
        "displayOrder": 9
      },
      {
        "code": "consultant",
        "label": "Consultant",
        "displayOrder": 10
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ProjectType",
    "description": "Classification of funded project types",
    "values": [
      {
        "code": "research",
        "label": "Research",
        "displayOrder": 1
      },
      {
        "code": "instruction",
        "label": "Instruction/Training",
        "displayOrder": 2
      },
      {
        "code": "public_service",
        "label": "Public Service",
        "displayOrder": 3
      },
      {
        "code": "fellowship",
        "label": "Fellowship",
        "displayOrder": 4
      },
      {
        "code": "equipment",
        "label": "Equipment",
        "displayOrder": 5
      },
      {
        "code": "conference",
        "label": "Conference/Workshop",
        "displayOrder": 6
      },
      {
        "code": "other",
        "label": "Other",
        "displayOrder": 7
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ContactType",
    "description": "Contact method classification for persons and organizations",
    "values": [
      {
        "code": "email",
        "label": "Email",
        "displayOrder": 1
      },
      {
        "code": "phone",
        "label": "Phone",
        "displayOrder": 2
      },
      {
        "code": "fax",
        "label": "Fax",
        "displayOrder": 3
      },
      {
        "code": "address",
        "label": "Mailing Address",
        "displayOrder": 4
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "COIRelationship",
    "description": "Types of conflict of interest relationships",
    "values": [
      {
        "code": "equity",
        "label": "Equity Interest",
        "displayOrder": 1
      },
      {
        "code": "consulting",
        "label": "Consulting Agreement",
        "displayOrder": 2
      },
      {
        "code": "board",
        "label": "Board Membership",
        "displayOrder": 3
      },
      {
        "code": "ip",
        "label": "Intellectual Property",
        "displayOrder": 4
      },
      {
        "code": "travel",
        "label": "Sponsored Travel",
        "displayOrder": 5
      },
      {
        "code": "other",
        "label": "Other",
        "displayOrder": 6
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "FundType",
    "description": "Source category for project funding",
    "values": [
      {
        "code": "sponsored",
        "label": "Sponsored Research",
        "displayOrder": 1
      },
      {
        "code": "institutional",
        "label": "Institutional Funds",
        "displayOrder": 2
      },
      {
        "code": "cost_share",
        "label": "Cost Share",
        "displayOrder": 3
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "TransactionType",
    "description": "Financial transaction classification (reserved for post-award)",
    "values": [
      {
        "code": "expenditure",
        "label": "Expenditure",
        "displayOrder": 1
      },
      {
        "code": "encumbrance",
        "label": "Encumbrance",
        "displayOrder": 2
      },
      {
        "code": "revenue",
        "label": "Revenue",
        "displayOrder": 3
      },
      {
        "code": "transfer",
        "label": "Transfer",
        "displayOrder": 4
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "DeliverableType",
    "description": "Project deliverable categories (reserved for post-award)",
    "values": [
      {
        "code": "progress_report",
        "label": "Progress Report",
        "displayOrder": 1
      },
      {
        "code": "final_report",
        "label": "Final Report",
        "displayOrder": 2
      },
      {
        "code": "financial_report",
        "label": "Financial Report",
        "displayOrder": 3
      },
      {
        "code": "invention_report",
        "label": "Invention Report",
        "displayOrder": 4
      },
      {
        "code": "other",
        "label": "Other Deliverable",
        "displayOrder": 5
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ModEventType",
    "description": "Award modification event types (reserved for post-award)",
    "values": [
      {
        "code": "no_cost_ext",
        "label": "No-Cost Extension",
        "displayOrder": 1
      },
      {
        "code": "supplemental",
        "label": "Supplemental Funding",
        "displayOrder": 2
      },
      {
        "code": "budget_realloc",
        "label": "Budget Reallocation",
        "displayOrder": 3
      },
      {
        "code": "pi_change",
        "label": "Change of PI",
        "displayOrder": 4
      },
      {
        "code": "scope_change",
        "label": "Change in Scope",
        "displayOrder": 5
      },
      {
        "code": "reduction",
        "label": "Funding Reduction",
        "displayOrder": 6
      },
      {
        "code": "termination",
        "label": "Early Termination",
        "displayOrder": 7
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ProposalCategory",
    "description": "Proposal submission type classification",
    "values": [
      {
        "code": "full",
        "label": "Full Proposal",
        "displayOrder": 1
      },
      {
        "code": "preliminary",
        "label": "Preliminary/Pre-Proposal",
        "displayOrder": 2
      },
      {
        "code": "subproject",
        "label": "Sub-Project",
        "displayOrder": 3
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ProposalActionType",
    "description": "Action type of a proposal submission",
    "values": [
      {
        "code": "new",
        "label": "New",
        "displayOrder": 1
      },
      {
        "code": "renewal",
        "label": "Renewal",
        "displayOrder": 2
      },
      {
        "code": "continuation",
        "label": "Continuation",
        "displayOrder": 3
      },
      {
        "code": "supplement",
        "label": "Supplement",
        "displayOrder": 4
      },
      {
        "code": "revision",
        "label": "Revision",
        "displayOrder": 5
      },
      {
        "code": "resubmission",
        "label": "Resubmission",
        "displayOrder": 6
      },
      {
        "code": "transfer_in",
        "label": "Transfer-in",
        "displayOrder": 7
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "AgreementType",
    "description": "Funding agreement type classification",
    "values": [
      {
        "code": "grant",
        "label": "Grant",
        "displayOrder": 1
      },
      {
        "code": "cooperative",
        "label": "Cooperative Agreement",
        "displayOrder": 2
      },
      {
        "code": "contract",
        "label": "Contract",
        "displayOrder": 3
      },
      {
        "code": "subaward",
        "label": "Subaward",
        "displayOrder": 4
      },
      {
        "code": "other",
        "label": "Other",
        "displayOrder": 5
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "CampusType",
    "description": "Campus or facility type for F&A rate determination",
    "values": [
      {
        "code": "on_campus",
        "label": "On-Campus",
        "displayOrder": 1
      },
      {
        "code": "off_campus",
        "label": "Off-Campus",
        "displayOrder": 2
      },
      {
        "code": "ag_research",
        "label": "Ag & Forestry Research",
        "displayOrder": 3
      },
      {
        "code": "ag_non_research",
        "label": "Ag & Forestry Non-Research",
        "displayOrder": 4
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "CampusLocation",
    "description": "University of Idaho campus locations",
    "values": [
      {
        "code": "moscow",
        "label": "Moscow",
        "displayOrder": 1
      },
      {
        "code": "boise",
        "label": "Boise",
        "displayOrder": 2
      },
      {
        "code": "cda",
        "label": "Coeur d'Alene",
        "displayOrder": 3
      },
      {
        "code": "if",
        "label": "Idaho Falls",
        "displayOrder": 4
      },
      {
        "code": "tf",
        "label": "Twin Falls",
        "displayOrder": 5
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "SponsorRegulatory",
    "description": "Federal regulatory frameworks applicable to sponsors",
    "values": [
      {
        "code": "dod",
        "label": "Department of Defense (DoD)",
        "displayOrder": 1
      },
      {
        "code": "nist_sp800",
        "label": "NIST SP 800-171",
        "displayOrder": 2
      },
      {
        "code": "cmmc",
        "label": "CMMC",
        "displayOrder": 3
      },
      {
        "code": "cui",
        "label": "Controlled Unclassified Information (CUI)",
        "displayOrder": 4
      },
      {
        "code": "doe",
        "label": "Department of Energy (DOE)",
        "displayOrder": 5
      },
      {
        "code": "nasa",
        "label": "NASA",
        "displayOrder": 6
      },
      {
        "code": "nih",
        "label": "National Institutes of Health (NIH)",
        "displayOrder": 7
      },
      {
        "code": "nsf",
        "label": "National Science Foundation (NSF)",
        "displayOrder": 8
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ExportControl",
    "description": "Export control risk factor classification",
    "values": [
      {
        "code": "foreign_involvement",
        "label": "Foreign National Involvement",
        "displayOrder": 1
      },
      {
        "code": "military_defense",
        "label": "Military / Defense Related",
        "displayOrder": 2
      },
      {
        "code": "pub_restrictions",
        "label": "Publication Restrictions",
        "displayOrder": 3
      },
      {
        "code": "foreign_national_id",
        "label": "Foreign National Identification",
        "displayOrder": 4
      },
      {
        "code": "work_outside_us",
        "label": "Work Performed Outside the US",
        "displayOrder": 5
      },
      {
        "code": "intl_travel",
        "label": "International Travel",
        "displayOrder": 6
      },
      {
        "code": "controlled_tech",
        "label": "Controlled Technology / Items",
        "displayOrder": 7
      },
      {
        "code": "uas_drone",
        "label": "UAS / Drone Research",
        "displayOrder": 8
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ResearchInstitute",
    "description": "University of Idaho research institute affiliations",
    "values": [
      {
        "code": "iids",
        "label": "Institute for Interdisciplinary Data Sciences (IIDS)",
        "displayOrder": 1
      },
      {
        "code": "imci",
        "label": "Institute for Modeling Collaboration & Innovation (IMCI)",
        "displayOrder": 2
      },
      {
        "code": "ari",
        "label": "Aquaculture Research Institute (ARI)",
        "displayOrder": 3
      },
      {
        "code": "iwrri",
        "label": "Idaho Water Resources Research Institute (IWRRI)",
        "displayOrder": 4
      },
      {
        "code": "igs",
        "label": "Idaho Geological Survey (IGS)",
        "displayOrder": 5
      },
      {
        "code": "caes",
        "label": "Center for Advanced Energy Studies (CAES)",
        "displayOrder": 6
      },
      {
        "code": "ihhe",
        "label": "Institute for Health in the Human Ecosystem (IHHE)",
        "displayOrder": 7
      },
      {
        "code": "ics",
        "label": "Institute for Cyber Security (ICS)",
        "displayOrder": 8
      },
      {
        "code": "na",
        "label": "Not Applicable",
        "displayOrder": 9
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "RequirementCategory",
    "description": "Categories for requirements extracted from RFAs",
    "values": [
      {
        "code": "document",
        "label": "Document",
        "displayOrder": 1,
        "description": "Required proposal document or attachment"
      },
      {
        "code": "formatting",
        "label": "Formatting",
        "displayOrder": 2,
        "description": "Page/font/margin formatting specification"
      },
      {
        "code": "eligibility",
        "label": "Eligibility",
        "displayOrder": 3,
        "description": "Applicant eligibility requirement"
      },
      {
        "code": "review_criterion",
        "label": "Review Criterion",
        "displayOrder": 4,
        "description": "Merit review criterion"
      },
      {
        "code": "budget_constraint",
        "label": "Budget Constraint",
        "displayOrder": 5,
        "description": "Budget limitation or rule"
      },
      {
        "code": "submission",
        "label": "Submission",
        "displayOrder": 6,
        "description": "Submission portal or format requirement"
      },
      {
        "code": "deadline",
        "label": "Deadline",
        "displayOrder": 7,
        "description": "Submission or review deadline"
      },
      {
        "code": "compliance",
        "label": "Compliance",
        "displayOrder": 8,
        "description": "Regulatory or policy compliance requirement"
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "ChecklistStatus",
    "description": "Completion status for proposal checklist items",
    "values": [
      {
        "code": "not_started",
        "label": "Not Started",
        "displayOrder": 1,
        "description": "Work has not begun on this item"
      },
      {
        "code": "in_progress",
        "label": "In Progress",
        "displayOrder": 2,
        "description": "Work is underway"
      },
      {
        "code": "complete",
        "label": "Complete",
        "displayOrder": 3,
        "description": "Item has been completed"
      },
      {
        "code": "not_applicable",
        "label": "Not Applicable",
        "displayOrder": 4,
        "description": "Item does not apply to this proposal"
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "AppointmentType",
    "description": "Personnel appointment types for APM 45.22 PI/Co-PI eligibility evaluation",
    "values": [
      {
        "code": "tenured",
        "label": "Tenured",
        "displayOrder": 1
      },
      {
        "code": "tenure_track",
        "label": "Tenure-Track",
        "displayOrder": 2
      },
      {
        "code": "non_tenure_track",
        "label": "Non-Tenure-Track",
        "displayOrder": 3
      },
      {
        "code": "research_faculty",
        "label": "Research Faculty",
        "displayOrder": 4
      },
      {
        "code": "extension_faculty",
        "label": "Extension Faculty",
        "displayOrder": 5
      },
      {
        "code": "librarian_faculty",
        "label": "Librarian Faculty",
        "displayOrder": 6
      },
      {
        "code": "clinical_faculty",
        "label": "Clinical Faculty",
        "displayOrder": 7
      },
      {
        "code": "visiting_faculty",
        "label": "Visiting Faculty",
        "displayOrder": 8
      },
      {
        "code": "emeritus",
        "label": "Emeritus",
        "displayOrder": 9
      },
      {
        "code": "postdoctoral_fellow",
        "label": "Postdoctoral Fellow",
        "displayOrder": 10
      },
      {
        "code": "research_scientist",
        "label": "Research Scientist",
        "displayOrder": 11
      },
      {
        "code": "staff",
        "label": "Staff",
        "displayOrder": 12
      },
      {
        "code": "graduate_student",
        "label": "Graduate Student",
        "displayOrder": 13
      },
      {
        "code": "undergraduate_student",
        "label": "Undergraduate Student",
        "displayOrder": 14
      },
      {
        "code": "external_collaborator",
        "label": "External Collaborator",
        "displayOrder": 15
      }
    ]
  },
  {
    "domain": "research-admin",
    "application": "OpenERA",
    "group": "FacultyRank",
    "description": "Faculty rank levels",
    "values": [
      {
        "code": "professor",
        "label": "Professor",
        "displayOrder": 1
      },
      {
        "code": "assoc_professor",
        "label": "Associate Professor",
        "displayOrder": 2
      },
      {
        "code": "asst_professor",
        "label": "Assistant Professor",
        "displayOrder": 3
      },
      {
        "code": "lecturer",
        "label": "Lecturer",
        "displayOrder": 4
      },
      {
        "code": "senior_lecturer",
        "label": "Senior Lecturer",
        "displayOrder": 5
      },
      {
        "code": "clinical_professor",
        "label": "Clinical Professor",
        "displayOrder": 6
      },
      {
        "code": "research_sci_i",
        "label": "Research Scientist I",
        "displayOrder": 7
      },
      {
        "code": "research_sci_ii",
        "label": "Research Scientist II",
        "displayOrder": 8
      },
      {
        "code": "research_sci_iii",
        "label": "Research Scientist III",
        "displayOrder": 9
      }
    ]
  }
];
