// Auto-generated by scripts/refresh-commit-dates.ts.
// Do not edit by hand — re-run `npm run refresh:commit-dates` to refresh.
//
// Maps project slug → derived facts about its repository (currently
// just last commit date on the default branch). Verification rules in
// lib/portfolio-verification.ts read from this file. When an entry is
// missing, commit-cadence rules degrade to a warning rather than a hard
// failure (see ADR 0001 — "skip gracefully").

export interface PortfolioMetaEntry {
  lastCommitDate?: string; // ISO 8601
  fetchedAt?: string;      // ISO 8601 — when the value was last refreshed
}

export const portfolioMeta: Record<string, PortfolioMetaEntry> = {
  "audit-dashboard": { lastCommitDate: "2026-05-30T23:24:10Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "dgx-stack": { lastCommitDate: "2026-07-23T00:54:05Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "dissertation-formatter": { lastCommitDate: "2026-09-10T17:57:58Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "execord": { lastCommitDate: "2026-06-12T15:25:21Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "mindrouter": { lastCommitDate: "2026-09-14T12:22:51Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "mindrouter-video-storyboard": { lastCommitDate: "2026-09-14T12:22:51Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "openera": { lastCommitDate: "2026-09-15T18:57:51Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "processmapping": { lastCommitDate: "2026-09-15T19:03:55Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "retroactive-payment-requests": { lastCommitDate: "2026-03-10T19:21:20Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "rfd-career": { lastCommitDate: "2026-06-09T22:52:23Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "rfd-companion": { lastCommitDate: "2026-09-14T22:12:11Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "sem-experiential": { lastCommitDate: "2026-07-14T14:53:42Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "sidearm-pipeline": { lastCommitDate: "2026-09-11T07:35:52Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "stratplan": { lastCommitDate: "2026-05-05T09:35:03Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "template-app": { lastCommitDate: "2026-05-05T20:06:00Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "ucm-daily-register": { lastCommitDate: "2026-09-14T21:16:50Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "universo": { lastCommitDate: "2026-09-14T21:39:28Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "vandalizer": { lastCommitDate: "2026-09-15T08:01:41Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
  "water-law-database": { lastCommitDate: "2026-03-04T22:50:30Z", fetchedAt: "2026-09-15T19:47:52.356Z" },
};
