// Auto-generated by scripts/refresh-commit-dates.ts.
// Do not edit by hand — re-run `npm run refresh:commit-dates` to refresh.
//
// Maps project slug → derived facts about its repository (currently
// just last commit date on the default branch). Verification rules in
// lib/portfolio-verification.ts read from this file. When an entry is
// missing, commit-cadence rules degrade to a warning rather than a hard
// failure (see ADR 0001 — "skip gracefully").

export interface PortfolioMetaEntry {
  lastCommitDate?: string; // ISO 8601
  fetchedAt?: string;      // ISO 8601 — when the value was last refreshed
}

export const portfolioMeta: Record<string, PortfolioMetaEntry> = {
  "dgx-stack": { lastCommitDate: "2026-04-15T21:50:03Z", fetchedAt: "2026-05-11T10:56:23.405Z" },
  "mindrouter": { lastCommitDate: "2026-05-03T13:52:46Z", fetchedAt: "2026-05-11T10:56:23.405Z" },
  "ucm-daily-register": { lastCommitDate: "2026-05-05T17:53:31Z", fetchedAt: "2026-05-11T10:56:23.405Z" },
  "vandalizer": { lastCommitDate: "2026-05-08T13:59:51Z", fetchedAt: "2026-05-11T10:56:23.405Z" },
};
