// Auto-generated by scripts/refresh-commit-dates.ts.
// Do not edit by hand — re-run `npm run refresh:commit-dates` to refresh.
//
// Maps project slug → derived facts about its repository (currently
// just last commit date on the default branch). Verification rules in
// lib/portfolio-verification.ts read from this file. When an entry is
// missing, commit-cadence rules degrade to a warning rather than a hard
// failure (see ADR 0001 — "skip gracefully").

export interface PortfolioMetaEntry {
  lastCommitDate?: string; // ISO 8601
  fetchedAt?: string;      // ISO 8601 — when the value was last refreshed
}

export const portfolioMeta: Record<string, PortfolioMetaEntry> = {
  "dgx-stack": { lastCommitDate: "2026-07-19T12:58:57Z", fetchedAt: "2026-07-20T10:45:06.658Z" },
  "mindrouter": { lastCommitDate: "2026-07-19T14:55:44Z", fetchedAt: "2026-07-20T10:45:06.658Z" },
  "ucm-daily-register": { lastCommitDate: "2026-07-18T16:51:28Z", fetchedAt: "2026-07-20T10:45:06.658Z" },
  "vandalizer": { lastCommitDate: "2026-07-19T15:02:16Z", fetchedAt: "2026-07-20T10:45:06.658Z" },
};
