import Link from "next/link";

export const metadata = {
  title:
    "Cautionary tale: Lovable vibe-coding security crisis · Institutional AI Initiative",
  description:
    "External signal informing UI's institutional posture on AI-assisted development: the 48-day Lovable exposure and what it means for UI governance.",
};

const keyStats = [
  { value: "48 days", label: "Projects exposed after Lovable closed the bug report" },
  { value: "$6.6B", label: "Lovable platform valuation at the time of disclosure" },
  { value: "40–62%", label: "AI-generated code found to contain vulnerabilities" },
  {
    value: "91.5%",
    label:
      "Vibe-coded apps with at least one AI hallucination-related flaw in Q1 2026",
  },
  {
    value: "87%",
    label: "Fortune 500 companies that have adopted vibe coding platforms",
  },
  {
    value: "60%",
    label:
      "Projected share of all new code that will be AI-generated by year-end 2026",
  },
];

const howUiDiffers = [
  "Every IIDS-coordinated intervention names an operational owner who is accountable for the outcome, not just the code.",
  "New UI applications start from TEMPLATE-app — JWT, RBAC, dependency scanning, CycloneDX SBOM, and an institutional review checklist baked in from day one.",
  "OIT holds a standards-review gate; IIDS-built tooling is evaluated before it propagates as an endorsed UI standard.",
  "AI inference for UI apps routes through MindRouter, which maintains an audit log of prompts, responses, and artifacts available for review.",
  "The portfolio at /portfolio is institutional visibility — shadow AI work gets surfaced rather than hidden, so a 48-day silent exposure cannot persist unobserved under this posture.",
];

export default function LovableCautionaryTalePage() {
  return (
    <article className="space-y-10">
      <nav className="text-sm text-gray-500">
        <Link href="/reports" className="hover:text-ui-gold-dark">
          Reports
        </Link>
        <span className="mx-2">/</span>
        <span className="text-ui-charcoal">
          Cautionary tale: Lovable vibe-coding security crisis
        </span>
      </nav>

      <header>
        <p className="text-xs font-semibold uppercase tracking-wider text-ui-gold-dark">
          A cautionary tale &middot; April 21, 2026
        </p>
        <h1 className="mt-2 text-3xl font-black tracking-tight text-brand-black">
          Vibe coding without institutional guardrails
        </h1>
        <p className="mt-3 max-w-3xl text-base text-gray-700">
          Lovable, an AI-powered coding platform valued at $6.6B, left thousands
          of its users&apos; projects exposed for 48 days after closing a bug
          report without escalation. Three documented breaches revealed source
          code, database credentials, and real user records.
        </p>
      </header>

      <section className="rounded-xl border border-gray-200 bg-white p-5">
        <p className="text-xs font-semibold uppercase tracking-wider text-gray-500">
          Source
        </p>
        <p className="mt-1 text-sm text-brand-black">
          <a
            href="https://thenextweb.com/news/lovable-vibe-coding-security-crisis-exposed"
            target="_blank"
            rel="noopener noreferrer"
            className="font-semibold text-brand-black underline decoration-clearwater underline-offset-4 hover:decoration-2"
          >
            &ldquo;Lovable left thousands of projects exposed for 48 days, and
            the vibe coding security crisis is only getting worse&rdquo;
          </a>
          <br />
          <span className="text-gray-600">
            Allison Steffens Herrera &middot; The Next Web &middot; April 21,
            2026
          </span>
        </p>
      </section>

      <section>
        <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-500">
          By the numbers
        </h2>
        <div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {keyStats.map((stat) => (
            <div
              key={stat.label}
              className="rounded-xl border border-gray-200 bg-white p-5"
            >
              <p className="text-3xl font-black text-brand-black">
                {stat.value}
              </p>
              <p className="mt-1 text-sm text-gray-600">{stat.label}</p>
            </div>
          ))}
        </div>
      </section>

      <blockquote className="rounded-xl border-l-0 border-t-4 border-brand-gold bg-brand-gold/5 p-6">
        <p className="text-lg italic leading-relaxed text-brand-black">
          &ldquo;The real risk of vibe coding isn&apos;t AI writing insecure
          code. It&apos;s humans shipping code they never had a chance to
          secure.&rdquo;
        </p>
        <footer className="mt-3 text-sm text-gray-600">
          &mdash; The Next Web, April 21, 2026
        </footer>
      </blockquote>

      <section className="grid gap-6 md:grid-cols-2">
        <div>
          <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-500">
            What happened
          </h2>
          <p className="mt-3 text-sm leading-relaxed text-gray-700">
            Lovable generates full-stack web apps from natural-language prompts.
            A broken-authorization vulnerability allowed thousands of hosted
            projects to leak source code, database credentials, and real user
            data. Among the affected: a Connected Women in AI project exposing
            names, job titles, LinkedIn profiles, and Stripe IDs; students from
            UC Berkeley and UC Davis; and employees at Nvidia, Microsoft, Uber,
            and Spotify. The bug was reported and initially closed without
            escalation &mdash; the exposure window was 48 days.
          </p>
        </div>
        <div>
          <h2 className="text-sm font-semibold uppercase tracking-wider text-gray-500">
            Why it matters for UI
          </h2>
          <p className="mt-3 text-sm leading-relaxed text-gray-700">
            This is a preview of what happens when AI-assisted application
            development scales across an institution without governance. No
            named owner. No review gate. No security standard. No audit trail.
            The application ships, the exposure ships with it, and the
            institution finds out after.
          </p>
        </div>
      </section>

      <section className="rounded-xl border border-brand-gold bg-brand-gold/5 p-6">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-brand-gold-dark">
          How UI&apos;s institutional posture differs
        </h2>
        <ul className="mt-3 space-y-2">
          {howUiDiffers.map((item) => (
            <li
              key={item}
              className="flex items-start gap-3 text-sm leading-relaxed text-brand-black"
            >
              <span
                aria-hidden="true"
                className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-gold"
              />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </section>
    </article>
  );
}
