import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import type { Pillar, Priority } from "../lib/strategic-plan/types";

const ROOT = join(__dirname, "..");
const SOURCE = join(
  ROOT,
  "vendor",
  "strategic-plan",
  "backend",
  "app",
  "data",
  "strategic_plan_data.json",
);
const OUT = join(ROOT, "lib", "strategic-plan", "catalog.ts");

function fail(msg: string): never {
  console.error(`[build-strategic-plan-catalog] ${msg}`);
  process.exit(1);
}

function readJson(path: string): any {
  if (!existsSync(path)) fail(`missing file: ${path}`);
  try {
    return JSON.parse(readFileSync(path, "utf-8"));
  } catch (e) {
    fail(`malformed JSON at ${path}: ${(e as Error).message}`);
  }
}

const HEADER = `// Auto-generated by scripts/build-strategic-plan-catalog.ts.
// Do not edit by hand — re-run \`npm run build:strategic-plan\` (or any \`npm run build\`)
// to regenerate from vendor/strategic-plan/.
`;

function main() {
  if (!existsSync(SOURCE)) {
    fail(
      `missing ${SOURCE}. Did you run \`git submodule update --init\`?`,
    );
  }

  const raw = readJson(SOURCE);
  if (!raw.pillars || typeof raw.pillars !== "object") {
    fail(`expected top-level "pillars" object in ${SOURCE}`);
  }

  const pillars: Pillar[] = [];
  const allPriorities: Priority[] = [];

  const pillarCodes = Object.keys(raw.pillars).sort();
  for (const code of pillarCodes) {
    const p = raw.pillars[code];
    if (!p || typeof p.name !== "string" || !p.priorities) {
      fail(`pillar ${code} is malformed`);
    }
    const priorityCodes = Object.keys(p.priorities).sort();
    const priorities: Priority[] = priorityCodes.map((pcode) => ({
      code: pcode,
      pillar: code,
      text: String(p.priorities[pcode]),
    }));
    allPriorities.push(...priorities);
    pillars.push({
      code,
      name: String(p.name),
      priorities,
    });
  }

  const outDir = dirname(OUT);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  writeFileSync(
    OUT,
    HEADER +
      `import type { Pillar, Priority } from "./types";\n\n` +
      `export const pillars: Pillar[] = ${JSON.stringify(pillars, null, 2)};\n\n` +
      `export const priorities: Priority[] = ${JSON.stringify(allPriorities, null, 2)};\n\n` +
      `export function getPillar(code: string): Pillar | undefined {\n` +
      `  return pillars.find((p) => p.code === code);\n` +
      `}\n\n` +
      `export function getPriority(code: string): Priority | undefined {\n` +
      `  return priorities.find((p) => p.code === code);\n` +
      `}\n`,
  );

  console.log(
    `[build-strategic-plan-catalog] ${pillars.length} pillars, ${allPriorities.length} priorities → ${OUT}`,
  );
}

main();
