// scripts/refresh-commit-dates.ts
//
// Refreshes lib/portfolio-meta.ts by hitting the GitHub API for each
// intervention with a repoUrl and recording the most recent commit
// date on the default branch.
//
// Used by the verifier (lib/portfolio-verification.ts) to enforce the
// commit-cadence rules in ADR 0001 — `building` requires a commit
// within 60 days, `prototype` requires either >30 days quiet or
// featureComplete:true, `maintained` requires 90+ days quiet.
//
// Auth:
//   Uses GITHUB_TOKEN if set (avoids the 60 req/hr unauth rate limit).
//   In CI, the GITHUB_TOKEN secret is automatically available.
//
// Usage:
//   npm run refresh:commit-dates
//
// Output:
//   Overwrites lib/portfolio-meta.ts. The file is committed; the
//   weekly GitHub Action opens a PR when contents change.

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { interventions } from "../lib/portfolio.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = join(__dirname, "..", "lib", "portfolio-meta.ts");

const token = process.env.GITHUB_TOKEN;
const headers: Record<string, string> = {
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
  "User-Agent": "aispeg-refresh-commit-dates",
};
if (token) headers.Authorization = `Bearer ${token}`;

interface RepoInfo {
  owner: string;
  repo: string;
}

function parseRepoUrl(url: string): RepoInfo | null {
  // https://github.com/owner/repo or https://github.com/owner/repo.git
  const match = url.match(/^https:\/\/github\.com\/([^/]+)\/([^/.]+)/);
  if (!match) return null;
  return { owner: match[1]!, repo: match[2]! };
}

interface CommitResult {
  slug: string;
  lastCommitDate: string | null;
  error?: string;
}

async function fetchLastCommitDate(
  slug: string,
  repoUrl: string
): Promise<CommitResult> {
  const info = parseRepoUrl(repoUrl);
  if (!info) {
    return { slug, lastCommitDate: null, error: `unparseable repoUrl: ${repoUrl}` };
  }

  // GET /repos/{owner}/{repo} returns default_branch + pushed_at;
  // pushed_at is good enough for cadence rules and avoids a second
  // call to fetch a specific commit.
  const url = `https://api.github.com/repos/${info.owner}/${info.repo}`;
  const res = await fetch(url, { headers });

  if (res.status === 404) {
    return { slug, lastCommitDate: null, error: "repo not found (private without token, or deleted)" };
  }
  if (!res.ok) {
    return {
      slug,
      lastCommitDate: null,
      error: `${res.status} ${res.statusText}`,
    };
  }

  const data = (await res.json()) as { pushed_at?: string };
  if (!data.pushed_at) {
    return { slug, lastCommitDate: null, error: "no pushed_at on response" };
  }
  return { slug, lastCommitDate: data.pushed_at };
}

function emit(results: CommitResult[]): string {
  const fetchedAt = new Date().toISOString();
  const entries = results
    .filter((r) => r.lastCommitDate)
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map(
      (r) =>
        `  "${r.slug}": { lastCommitDate: "${r.lastCommitDate}", fetchedAt: "${fetchedAt}" },`
    )
    .join("\n");

  return `// Auto-generated by scripts/refresh-commit-dates.ts.
// Do not edit by hand — re-run \`npm run refresh:commit-dates\` to refresh.
//
// Maps intervention slug → derived facts about its repository (currently
// just last commit date on the default branch). Verification rules in
// lib/portfolio-verification.ts read from this file. When an entry is
// missing, commit-cadence rules degrade to a warning rather than a hard
// failure (see ADR 0001 — "skip gracefully").

export interface PortfolioMetaEntry {
  lastCommitDate?: string; // ISO 8601
  fetchedAt?: string;      // ISO 8601 — when the value was last refreshed
}

export const portfolioMeta: Record<string, PortfolioMetaEntry> = {
${entries}
};
`;
}

async function main(): Promise<void> {
  if (!token) {
    console.warn("GITHUB_TOKEN not set — using unauthenticated requests (60/hr cap; private repos will 404).");
  }

  const targets = interventions.filter((i) => i.repoUrl);
  console.log(`Refreshing commit dates for ${targets.length} interventions with a repoUrl ...\n`);

  const results: CommitResult[] = [];
  for (const i of targets) {
    const r = await fetchLastCommitDate(i.slug, i.repoUrl!);
    results.push(r);
    if (r.error) {
      console.warn(`  ! ${i.slug.padEnd(28)} ${r.error}`);
    } else {
      console.log(`  ↳ ${i.slug.padEnd(28)} ${r.lastCommitDate}`);
    }
  }

  writeFileSync(OUTPUT_PATH, emit(results), "utf8");
  const ok = results.filter((r) => r.lastCommitDate).length;
  const failed = results.length - ok;
  console.log(`\nWrote ${ok} entries to lib/portfolio-meta.ts (${failed} failed).`);
}

main().catch((err) => {
  console.error("refresh-commit-dates failed:", err);
  process.exit(1);
});
