// Auto-generated by scripts/build-strategic-plan-catalog.ts.
// Do not edit by hand — re-run `npm run build:strategic-plan` (or any `npm run build`)
// to regenerate from vendor/strategic-plan/.
import type { Pillar, Priority } from "./types";

export const pillars: Pillar[] = [
  {
    "code": "A",
    "name": "Ignite Student Success",
    "priorities": [
      {
        "code": "A.1",
        "pillar": "A",
        "text": "Provide a high-impact education with a focus on delivering the best value in the West"
      },
      {
        "code": "A.2",
        "pillar": "A",
        "text": "Reimagine the first-year experience with technology-enhanced support"
      },
      {
        "code": "A.3",
        "pillar": "A",
        "text": "Teach students how to apply AI in their disciplines and their lives"
      },
      {
        "code": "A.4",
        "pillar": "A",
        "text": "Foster a welcoming campus experience that prioritizes connection, engagement, and student well-being"
      }
    ]
  },
  {
    "code": "B",
    "name": "Drive 100% Experiential Learning",
    "priorities": [
      {
        "code": "B.1",
        "pillar": "B",
        "text": "Expand research learning opportunities"
      },
      {
        "code": "B.2",
        "pillar": "B",
        "text": "Strengthen workforce and community-based partnerships and student support"
      },
      {
        "code": "B.3",
        "pillar": "B",
        "text": "Build the systems to deliver 100% student participation in experiential learning"
      }
    ]
  },
  {
    "code": "C",
    "name": "Adapt the Educational Model",
    "priorities": [
      {
        "code": "C.1",
        "pillar": "C",
        "text": "Deliver the Vandal experience to all learners"
      },
      {
        "code": "C.2",
        "pillar": "C",
        "text": "Expand academic reach and regional impact through targeted investment"
      },
      {
        "code": "C.3",
        "pillar": "C",
        "text": "Develop a transfer pathway network"
      },
      {
        "code": "C.4",
        "pillar": "C",
        "text": "Expand continuing and adult education to focus on in-demand careers"
      }
    ]
  },
  {
    "code": "D",
    "name": "Harness Research Innovation and Partnership",
    "priorities": [
      {
        "code": "D.1",
        "pillar": "D",
        "text": "Establish high-impact research focus areas"
      },
      {
        "code": "D.2",
        "pillar": "D",
        "text": "Invest in research infrastructure and support"
      },
      {
        "code": "D.3",
        "pillar": "D",
        "text": "Strengthen coordination with industry partners"
      },
      {
        "code": "D.4",
        "pillar": "D",
        "text": "Increase collaborations with Idaho agencies, the Legislature, and other educational institutions to serve Idaho"
      },
      {
        "code": "D.5",
        "pillar": "D",
        "text": "Address Idaho's healthcare worker shortage"
      }
    ]
  },
  {
    "code": "E",
    "name": "Optimize Operational Excellence",
    "priorities": [
      {
        "code": "E.1",
        "pillar": "E",
        "text": "Create a data warehouse"
      },
      {
        "code": "E.2",
        "pillar": "E",
        "text": "Simplify and automate processes through AI"
      },
      {
        "code": "E.3",
        "pillar": "E",
        "text": "Attract, retain, reward, and support the best faculty and staff"
      },
      {
        "code": "E.4",
        "pillar": "E",
        "text": "Build a culture of efficient collaboration and execution around projects"
      }
    ]
  }
];

export const priorities: Priority[] = [
  {
    "code": "A.1",
    "pillar": "A",
    "text": "Provide a high-impact education with a focus on delivering the best value in the West"
  },
  {
    "code": "A.2",
    "pillar": "A",
    "text": "Reimagine the first-year experience with technology-enhanced support"
  },
  {
    "code": "A.3",
    "pillar": "A",
    "text": "Teach students how to apply AI in their disciplines and their lives"
  },
  {
    "code": "A.4",
    "pillar": "A",
    "text": "Foster a welcoming campus experience that prioritizes connection, engagement, and student well-being"
  },
  {
    "code": "B.1",
    "pillar": "B",
    "text": "Expand research learning opportunities"
  },
  {
    "code": "B.2",
    "pillar": "B",
    "text": "Strengthen workforce and community-based partnerships and student support"
  },
  {
    "code": "B.3",
    "pillar": "B",
    "text": "Build the systems to deliver 100% student participation in experiential learning"
  },
  {
    "code": "C.1",
    "pillar": "C",
    "text": "Deliver the Vandal experience to all learners"
  },
  {
    "code": "C.2",
    "pillar": "C",
    "text": "Expand academic reach and regional impact through targeted investment"
  },
  {
    "code": "C.3",
    "pillar": "C",
    "text": "Develop a transfer pathway network"
  },
  {
    "code": "C.4",
    "pillar": "C",
    "text": "Expand continuing and adult education to focus on in-demand careers"
  },
  {
    "code": "D.1",
    "pillar": "D",
    "text": "Establish high-impact research focus areas"
  },
  {
    "code": "D.2",
    "pillar": "D",
    "text": "Invest in research infrastructure and support"
  },
  {
    "code": "D.3",
    "pillar": "D",
    "text": "Strengthen coordination with industry partners"
  },
  {
    "code": "D.4",
    "pillar": "D",
    "text": "Increase collaborations with Idaho agencies, the Legislature, and other educational institutions to serve Idaho"
  },
  {
    "code": "D.5",
    "pillar": "D",
    "text": "Address Idaho's healthcare worker shortage"
  },
  {
    "code": "E.1",
    "pillar": "E",
    "text": "Create a data warehouse"
  },
  {
    "code": "E.2",
    "pillar": "E",
    "text": "Simplify and automate processes through AI"
  },
  {
    "code": "E.3",
    "pillar": "E",
    "text": "Attract, retain, reward, and support the best faculty and staff"
  },
  {
    "code": "E.4",
    "pillar": "E",
    "text": "Build a culture of efficient collaboration and execution around projects"
  }
];

export function getPillar(code: string): Pillar | undefined {
  return pillars.find((p) => p.code === code);
}

export function getPriority(code: string): Priority | undefined {
  return priorities.find((p) => p.code === code);
}
